apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: bustuk/nest-todo-backend
        ports:
        - containerPort: 3000
        resources: {}
        envFrom:
        - configMapRef:
            name: backend-cm
        - secretRef:
            name: db-secrets
