apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: bustuk/nest-backend
        ports:
        - containerPort: 3000
        resources: {}
        env:
        - name: DB_HOST
          value: "mysql"
