version: "3.9"
services:
  frontend:
    container_name: vue-frontend-img
    image: vue-frontentd   #rejestr/nazwa_uzytkownika/nazwa_obrazu[:tag]
    build:
      context: ./frontend/
      dockerfile: Dockerfile
      args:
        - BUILD_VERSION=2.0
    # env_file:
    #   - ./config/env_var.env
    ports:
      - "1337:80"
  backend:
    container_name: nest-backend-img
    image: nest-backend   #rejestr/nazwa_uzytkownika/nazwa_obrazu[:tag]
    build:
      context: ./backend/
      dockerfile: Dockerfile
      args:
        - BUILD_VERSION=2.0
    # env_file:
    #   - ./config/env_var.env
    ports:
      - "3000:3000"
    depends_on:
      - db
    # redis:
    #   condition: service_completed_successfully
    # volumes:
    #   - type: volume
    #     source: mydata
    #     target: /data
    #     volume:
    #       nocopy: true
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: db
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      - '3306'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  # redis:
  #   image: "redis:alpine"
# volumes:
#   mydata: