version: "3"
services:
  frontend:
    container_name: vue-frontend-container
    image: bustuk/vue-todo-frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
      args:
        - BUILD_VERSION=2.0
    ports:
      - "1337:80"
    depends_on:
      - backend
  backend:
    container_name: nest-backend-container
    image: bustuk/nest-todo-backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
      args:
        - BUILD_VERSION=2.0
    environment:
      DB_HOST: mysql
    ports:
      - "3000:3000"
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: db
    ports:
      - '3306:3306'