version: "3"
services:
  frontend:
    container_name: vue-frontend-container
    image: vue-frontentd
    build:
      context: ./frontend/
      dockerfile: Dockerfile
      args:
        - BUILD_VERSION=2.0
    # env_file:
    #   - ./config/env_var.env
    ports:
      - "1337:80"
    depends_on:
      - backend
  backend:
    container_name: nest-backend-container
    image: nest-backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
      args:
        - BUILD_VERSION=2.0
    # env_file:
    #   - ./config/env_var.env
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    # redis:
    #   condition: service_completed_successfully
    # volumes:
    #   - type: volume
    #     source: mydata
    #     target: /data
    #     volume:
    #       nocopy: true
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: db
    ports:
      - '3306:3306'
    # expose:
    #   - '3306'
  # redis:
  #   image: "redis:alpine"
# volumes:
#   mydata: