apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: "mysql:8.0"
        name: mysql
        envFrom:
        - configMapRef:
            name: db-cm
        - secretRef:
            name: db-secrets
        ports:
        - containerPort: 3306
          name: example
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: "/var/lib/mysql"
        resources: {}
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim