apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  DB_PASSWORD: ZXhhbXBsZQ== # example - change this
  MYSQL_ROOT_PASSWORD: ZXhhbXBsZQ== # example - change this
  DB_USER: cm9vdA== # root - change this